---
dependencies:
  avatar_glow: ^2.0.2
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.10
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.0.5
  reorderable_grid_view: ^2.2.8
  speech_to_text: ^6.4.0
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.0.5 <4.0.0'
flutter:
  assets:
    - images/owl.png
    - images/school.png
  uses-material-design: true
name: seats_app
publish_to: none
version: 1.0.0+1