// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCthmmEqVeAtX8-T9CAbW3nu_KeOSbwE',
    appId: '1:978199260460:web:2c27f527bfa0cc49d7d089',
    messagingSenderId: '978199260460',
    projectId: 'seats-app-firebase',
    authDomain: 'seats-app-firebase.firebaseapp.com',
    storageBucket: 'seats-app-firebase.appspot.com',
    measurementId: 'G-BFC8ZSFKMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_RmFdifRXBWtRKOKUicsU9Doc2oh6glk',
    appId: '1:978199260460:android:785fd492af2568b6d7d089',
    messagingSenderId: '978199260460',
    projectId: 'seats-app-firebase',
    storageBucket: 'seats-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVW_GciJ9t3nEUsx-fbI-ebO4L3Rk8qDM',
    appId: '1:978199260460:ios:33fe45be7990b1f0d7d089',
    messagingSenderId: '978199260460',
    projectId: 'seats-app-firebase',
    storageBucket: 'seats-app-firebase.appspot.com',
    iosBundleId: 'com.example.seatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVW_GciJ9t3nEUsx-fbI-ebO4L3Rk8qDM',
    appId: '1:978199260460:ios:744144404e4250edd7d089',
    messagingSenderId: '978199260460',
    projectId: 'seats-app-firebase',
    storageBucket: 'seats-app-firebase.appspot.com',
    iosBundleId: 'com.example.seatsApp.RunnerTests',
  );
}
